### ISSUE TITLE
Source code does not include intent handler for ask.with.list

### ISSUE THREAD

**Issue by wisdal** [actions-on-google/dialogflow-helper-intents-nodejs#1]

**Comment by smishra2** [comment]
Assigning to @lucaswadedavis to remove references to it.

For using askWithList, check out the [conversation components sample](https://github.com/actions-on-google/conversation-components-nodejs/blob/master/dialogflow/functions/index.js#L105)

**Comment by wisdal** [comment]
Alright. Thanks for the pointer!
