### ISSUE TITLE
AskForPlace goes to reprompt

### ISSUE THREAD

**Issue by sudiptachatterjee** [actions-on-google/dialogflow-helper-intents-nodejs#8]
Ask for Place first asks with the context: 'To find a place to pick you up', but then if you say yes it goes back to the reprompt: 'Where would you like to be picked up?'.

I suspect this has the same problem as the Ask for Confirmation; inability to parse yes/no responses directly.

**Comment by lucaswadedavis** [comment]
Interesting. I'm looking into it. Thanks for reporting my friend.

**Comment by findzaatar** [comment]
@sudiptachatterjee 

Not exactly following the issue with the sample here? The prompt is working as intended in this scenario.
